### PR TITLE
feat: 用户名历史时间线

### PR DESCRIPTION
**Pull request by immccn123**
应该没什么问题 虽然时间线是调的库（

https://github.com/user-attachments/assets/a8a3503b-90ff-4889-9eb2-13d858e89c33

https://github.com/user-attachments/assets/e20e562b-9ba0-4bf1-aef2-8693a30c9872

### CODE REVIEW

**Comment by bohanjun** [comment]
Is it possible to reuse the timeline I written for the replies? This will help maintain the stylistic consistency.

**Comment by bohanjun** [comment]
And there's still some problem here: why is there so many exactly same snapshots?

**Comment by immccn123** [comment]
> And there's still a problem here: why is there so many exactly same snapshots?

My local database (for development) was corrupted by the $200-issue, so the data is dirty.

**Comment by smallfangqwq** [comment]
ping @wxh06

**Comment by wxh06** [comment]
ping @wbh07

前端还有什么修改意见吗

**Comment by bohanjun** [comment]
> ping @bohanjun
> 
> 
> 
> 前端还有什么修改意见吗

nope

**Pull request merged**
